stages:
  - build
  - deploy

amd64 nginx build:
  stage: yobasystems/alpine-docker:dind
  stage: build
  tags:
    - amd64
  script:
    - apk add --update git
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token "$DOCKER_REGISTRY" --password-stdin
    - cd alpine-nginx/ && docker build -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:master -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:latest -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:amd64 .
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:master
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:latest
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:amd64

amd64 nginx-git build:
  stage: yobasystems/alpine-docker:dind
  stage: build
  tags:
    - amd64
  script:
    - apk add --update git
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token "$DOCKER_REGISTRY" --password-stdin
    - cd alpine-nginx-git/ && docker build -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:git -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:amd64-git .
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:git
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:amd64-git

amd64 nginx-git-ssh build:
  stage: yobasystems/alpine-docker:dind
  stage: build
  tags:
    - amd64
  script:
    - apk add --update git
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token "$DOCKER_REGISTRY" --password-stdin
    - cd alpine-nginx-git-ssh/ && docker build -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:git-ssh -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:amd64-git-ssh .
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:git-ssh
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:amd64-git-ssh

arm64v8 nginx build:
  stage: yobasystems/alpine-docker:aarch64-dind
  stage: build
  tags:
    - aarch64
  script:
    - apk add --update git
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token "$DOCKER_REGISTRY" --password-stdin
    - cd alpine-nginx-aarch64/ && docker build -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm64v8 -t $DOCKER_REGISTRY_DOCKERHUB_REPO:arm64v8 -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm64v8 -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:aarch64 -t $DOCKER_REGISTRY_DOCKERHUB_REPO:aarch64 -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:aarch64 .
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm64v8
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:aarch64
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:arm64v8
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:aarch64
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm64v8
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:aarch64

arm64v8 nginx-git build:
  stage: yobasystems/alpine-docker:aarch64-dind
  stage: build
  tags:
    - aarch64
  script:
    - apk add --update git
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token "$DOCKER_REGISTRY" --password-stdin
    - cd alpine-nginx-git-aarch64/ && docker build -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm64v8-git -t $DOCKER_REGISTRY_DOCKERHUB_REPO:arm64v8-git -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm64v8-git -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:aarch64-git -t $DOCKER_REGISTRY_DOCKERHUB_REPO:aarch64-git -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:aarch64-git .
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm64v8-git
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:aarch64-git
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:arm64v8-git
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:aarch64-git
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm64v8-git
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:aarch64-git

arm64v8 nginx-git-ssh build:
  stage: yobasystems/alpine-docker:aarch64-dind
  stage: build
  tags:
    - aarch64
  script:
    - apk add --update git
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token "$DOCKER_REGISTRY" --password-stdin
    - cd alpine-nginx-git-ssh-aarch64/ && docker build -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm64v8-git-ssh -t $DOCKER_REGISTRY_DOCKERHUB_REPO:arm64v8-git-ssh -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm64v8-git-ssh -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:aarch64-git-ssh -t $DOCKER_REGISTRY_DOCKERHUB_REPO:aarch64-git-ssh -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:aarch64-git-ssh .
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm64v8-git-ssh
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:aarch64-git-ssh
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:arm64v8-git-ssh
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:aarch64-git-ssh
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm64v8-git-ssh
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:aarch64-git-ssh

arm32v7 nginx build:
  stage: yobasystems/alpine-docker:armhf-dind
  stage: build
  tags:
    - armhf
  script:
    - apk add --update git
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token "$DOCKER_REGISTRY" --password-stdin
    - cd alpine-nginx-armhf/ && docker build -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm32v7 -t $DOCKER_REGISTRY_DOCKERHUB_REPO:arm32v7 -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm32v7 -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:armhf -t $DOCKER_REGISTRY_DOCKERHUB_REPO:armhf -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:armhf .
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm32v7
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:armhf
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:arm32v7
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:armhf
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm32v7
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:armhf

arm32v7 nginx-git build:
  stage: yobasystems/alpine-docker:armhf-dind
  stage: build
  tags:
    - armhf
  script:
    - apk add --update git
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token "$DOCKER_REGISTRY" --password-stdin
    - cd alpine-nginx-git-armhf/ && docker build -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm32v7-git -t $DOCKER_REGISTRY_DOCKERHUB_REPO:arm32v7-git -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm32v7-git -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:armhf-git -t $DOCKER_REGISTRY_DOCKERHUB_REPO:armhf-git -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:armhf-git .
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm32v7-git
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:armhf-git
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:arm32v7-git
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:armhf-git
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm32v7-git
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:armhf-git

arm32v7 nginx-git-ssh build:
  stage: yobasystems/alpine-docker:armhf-dind
  stage: build
  tags:
    - armhf
  script:
    - apk add --update git
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token "$DOCKER_REGISTRY" --password-stdin
    - cd alpine-nginx-git-ssh-armhf/ && docker build -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm32v7-git-ssh -t $DOCKER_REGISTRY_DOCKERHUB_REPO:arm32v7-git-ssh -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm32v7-git-ssh -t $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:armhf-git-ssh -t $DOCKER_REGISTRY_DOCKERHUB_REPO:armhf-git-ssh -t $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:armhf-git-ssh .
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:arm32v7-git-ssh
    - docker push $DOCKER_REGISTRY/$DOCKER_REGISTRY_REPO:armhf-git-ssh
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:arm32v7-git-ssh
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:armhf-git-ssh
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:arm32v7-git-ssh
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io --password-stdin && docker push $DOCKER_REGISTRY_QUAY/$DOCKER_REGISTRY_QUAY_REPO:armhf-git-ssh

Github Mirror:
  stage: deploy
  tags:
    - deploy
  script:
    - git push --mirror https://$GITHUB_USERNAME:$GITHUB_PASSWORD@$GITHUB_REPO
    - git push https://$GITHUB_USERNAME:$GITHUB_PASSWORD@$GITHUB_REPO HEAD:master

Bitbucket Mirror:
  stage: deploy
  tags:
    - deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$BB_SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 'bitbucket.org' >> ~/.ssh/known_hosts
    - git push --mirror git@$BITBUCKET_REPO
    - git push git@$BITBUCKET_REPO HEAD:master
